---
- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 60 seconds for target connection to become reachable/usable."
      wait_for_connection:
  
    - name: "update apt packages."
      become: yes
      apt:
        update_cache: yes

    - name: "upgrade packages"
      become: yes
      apt:
        upgrade: yes

    - name: remove dependencies that are no longer required
      become: yes
      apt:
        autoremove: yes

    - name: "install dependencies."
      become: yes
      apt:
        name: ["nodejs", "npm"]
        state: latest
        update_cache: yes

    - name: "install pm2"
      become: yes
      npm:
        name: pm2
        global: yes
        production: yes
        state: present

    - name: "Create backend app directory"
      file:
        path: ~/backendApp
        state: directory
      
    - name: "Unarchive backend files"
      unarchive:
        src: ./files/artifact.tar.gz
        dest: ~/backendApp
        remote_src: True 

    - name: "Installing Node Dependencies and executing node app with pm2"
      shell: |
        cd ~/backendApp
        npm i
        pm2 stop default
        pm2 start npm -- start 

  roles:
    - deploy


  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"


# - name: "configuration play." 
#   hosts: web
#   user: ubuntu
#   gather_facts: false
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_host_key_checking: false
#     - ansible_stdout_callback: yaml
  


#   roles:
#     - deploy

#   environment:
#     NODE_ENV: production
#     VERSION: "1"
#     - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
#     - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
#     - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
#     - TYPEORM_PORT: 5432
#     - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
#     - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
#     - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
#     - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
#     - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  
